### ISSUE TITLE
Config file parser

### ISSUE THREAD

**Issue by chrisk314** [chrisk314/mesh-sphere-packing#7]
Add `.yaml` config file parser to control the behaviour of the program. Options which should be configurable are given in the below example config file:

```yaml
packing_file          :   ./results_particles_51.h5
domain_dimensions     :   +6.404275126503458e-03 +6.434790849171976e-03 +6.439336808378881e-03
pbc                   :   1 1 1
allow_overlaps        :   0
tetgen_rad_edge_ratio :   1.4
tetgen_min_angle      :   18.
tetgen_max_volume     :   1.0e-05
surf_mesh_factor      :   1.0e-01
```
